### ISSUE TITLE
[JENKINS-52231] Cant caccess Global tool configuration

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/instance-identity-plugin#156]
<p>Please find the stack trace when clicked on Global tool configuration</p>

<p> </p>

<p> </p>

<p>java.lang.AssertionError: InstanceIdentity is missing its singleton<br/>
 at org.jenkinsci.main.modules.instance_identity.InstanceIdentity.get(InstanceIdentity.java:133)<br/>
 at org.jenkinsci.main.modules.instance_identity.InstanceIdentityRSAProvider.getKeyPair(InstanceIdentityRSAProvider.java:23)<br/>
 at jenkins.model.identity.InstanceIdentityProvider$KeyTypes.get(InstanceIdentityProvider.java:161)<br/>
 at jenkins.model.identity.InstanceIdentityProvider$KeyTypes.getKeyPair(InstanceIdentityProvider.java:210)<br/>
 at jenkins.model.identity.IdentityRootAction.getUrlName(IdentityRootAction.java:42)<br/>
 at jenkins.model.Jenkins.getDynamic(Jenkins.java:3665)<br/>
 at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:707)<br/>
 at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)<br/>
 at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)<br/>
 at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:372)<br/>
 at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)<br/>
Caused: javax.servlet.ServletException<br/>
 at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:765)<br/>
 at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)<br/>
 at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)<br/>
 at org.kohsuke.stapler.Stapler.service(Stapler.java:238)<br/>
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)<br/>
 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)<br/>
 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)<br/>
 at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)<br/>
 at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:105)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)<br/>
 at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)<br/>
 at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)<br/>
 at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)<br/>
 at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)<br/>
 at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)<br/>
 at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)<br/>
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)<br/>
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)<br/>
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)<br/>
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)<br/>
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)<br/>
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)<br/>
 at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)<br/>
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)<br/>
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)<br/>
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)<br/>
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)<br/>
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)<br/>
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)<br/>
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)<br/>
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)<br/>
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)<br/>
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/>
 at java.base/java.lang.Thread.run(Thread.java:844)</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=pvinay3000">pvinay3000</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-52231" target="_blank">Cant caccess Global tool configuration</a></i></summary>
<i><ul>
<li><b>status</b>: In Progress
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: instance-identity-module
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-28
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Please find the stack trace when clicked on Global tool configuration</p>

<p> </p>

<p> </p>

<p>java.lang.AssertionError: InstanceIdentity is missing its singleton
 at org.jenkinsci.main.modules.instance_identity.InstanceIdentity.get(InstanceIdentity.java:133)
 at org.jenkinsci.main.modules.instance_identity.InstanceIdentityRSAProvider.getKeyPair(InstanceIdentityRSAProvider.java:23)
 at jenkins.model.identity.InstanceIdentityProvider$KeyTypes.get(InstanceIdentityProvider.java:161)
 at jenkins.model.identity.InstanceIdentityProvider$KeyTypes.getKeyPair(InstanceIdentityProvider.java:210)
 at jenkins.model.identity.IdentityRootAction.getUrlName(IdentityRootAction.java:42)
 at jenkins.model.Jenkins.getDynamic(Jenkins.java:3665)
 at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:707)
 at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
 at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
 at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:372)
 at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
Caused: javax.servlet.ServletException
 at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:765)
 at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
 at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
 at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
 at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:105)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
 at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
 at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
 at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
 at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 at java.base/java.lang.Thread.run(Thread.java:844)</p></pre>
</details>
</details>

**Comment by MarkEWaite** [comment]
Closing because I'm unable to duplicate the issue.
